#!name=missav
#!desc=missav网页净化

[Script]
missav.ads = type=http-response, pattern=^https?:\/\/missav\.(ws|live|com|ai)\/(?!(.*(api|login|cdn-cgi|verify|auth|captch|(\.(js|css|jpg|jpeg|png|webp|gif|zip|woff|woff2|m3u8|mp4|mov|m4v|avi|mkv|flv|rmvb|wmv|rm|asf|asx|mp3|json|ico|otf|ttf))))), script-path=https://ddgksf2013.top/scripts/missav.ads.js, requires-body=true, max-size=-1, timeout=60

[MITM]
hostname = %APPEND% missav.live, missav.ws, missav.ai, missav.com

