#!name=百度地图
#!desc=移除百度地图广告

[Body Rewrite]
http-response-jq ^https?:\/\/.*map\.baidu\.com\/.*govui\/rich_content '.data.posts.content=[]'
http-response-jq ^https?:\/\/httpdns\.baidubce\.com '.data["newclient.map.baidu.com"]={}'
http-response-jq ^https?:\/\/newclient\.map\.baidu\.com\/usercenter/mine/page 'del(.data.sport_card, .data.gold, .data.gold_coin_card, .data.shop)'
http-response-jq ^https?:\/\/newclient\.map\.baidu\.com\/living/nearby/hot-words\? '.Result.data=[]'

[Map Local]
# > 百度地图_搜索推广@ddgksf2013
^https?:\/\/newclient\.map\.baidu\.com\/client\/phpui.*qt=hw data-type=text data=" " status-code=200

# > 百度地图_开屏广告|首页左上角广告@ddgksf2013
^https?:\/\/newclient\.map\.baidu\.com\/client\/phpui2\/\?qt=ads data-type=text data=" " status-code=200

# > 百度地图_各种商业推广@ddgksf2013
^https?:\/\/newclient\.map\.baidu\.com\/client\/crossmarketing data-type=text data=" " status-code=200

# > 百度地图_我的页面地图动态@ddgksf2013
^https?:\/\/newclient\.map\.baidu\.com\/client\/usersystem\/home\/dynamic data-type=text data=" " status-code=200

# > 百度地图_TIPS@ddgksf2013
^https?:\/\/newclient\.map\.baidu\.com\/contributor-bus/bounty/tips data-type=text data=" " status-code=200

[MITM]
hostname = %APPEND% 180.76.76.200, newclient.map.baidu.com, httpdns.baidubce.com, ugc.map.baidu.com

